"""
FBX Material Slot Mapper Module
-------------------------------
1. Scans binary FBX files to detect internal Maya/3ds Max material slot names.
2. Configures .fbx.import files with fbx/importer=0 (native ufbx) and attaches
   the post-import script.
3. Generates _subresources blocks mapping every detected slot to a valid .tres material
   using nested brace depth tracking to prevent dangling parameters.
"""

import os
import re
from typing import Dict, Set, Tuple

IGNORED_DIRS = {".godot", ".git", "node_modules"}


def find_pack_materials(pack_root: str, project_root: str) -> Dict[str, str]:
    """
    Scans a pack's directory to index available .mat.tres and .tres materials.
    Returns a dict of { material_stem_lower: res:// path }.
    """
    mat_map = {}
    for root, dirs, files in os.walk(pack_root):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        for f in files:
            if f.endswith((".mat.tres", ".tres")) and not f.endswith(".mesh"):
                stem = f.replace(".mat.tres", "").replace(".tres", "").lower()
                rel_path = "res://" + os.path.relpath(os.path.join(root, f), project_root).replace("\\", "/")
                mat_map[stem] = rel_path
    return mat_map


def extract_fbx_material_slots(fbx_path: str) -> Set[str]:
    """
    Extracts all material slot names present in an FBX binary header.
    """
    slot_names = set()
    try:
        with open(fbx_path, "rb") as f:
            data = f.read(512 * 1024)

        for m in re.findall(b"([a-zA-Z0-9_-]+)\x00\x01Material", data):
            slot_names.add(m.decode("ascii", errors="ignore"))

        for m in re.findall(b"Material::([a-zA-Z0-9_-]+)", data):
            slot_names.add(m.decode("ascii", errors="ignore"))

        for m in re.findall(b"Material[\x00-\x10]+([a-zA-Z0-9_ -]{2,40})[\x00-\x10]+(?:FbxSurfaceLambert|FbxSurfacePhong|Material)", data):
            slot_names.add(m.decode("ascii", errors="ignore").strip())

        for m in re.findall(b"([a-zA-Z0-9_ -]{2,40})\x00\x01(?:FbxSurfaceLambert|FbxSurfacePhong)", data):
            slot_names.add(m.decode("ascii", errors="ignore").strip())

        for m in re.findall(b"Material\x00+([a-zA-Z0-9_-]+)", data):
            slot_names.add(m.decode("ascii", errors="ignore"))
    except Exception:
        pass

    # Standard fallback slots commonly generated by Maya/Max/ufbx
    slot_names.update([
        "default",
        "Base_Lambert",
        "lambert",
        "lambert1",
        "standardSurface1",
        "MAT_01A",
        "MAT_01B",
        "COLOR",
        "Polygon",
        "Polygon_Generic_01A",
        "Scifi_Cybercity_Main",
        "custom_lambert",
        "pasted__lambert4SG3",
        "roboguy_lambert4SG3",
        "roboguy_lambert4SG11",
        "roboguy_lambert4SG12",
        "roboguy_lambert4SG13",
        "roboguy_lambert4SG14",
        "roboguy_lambert4SG15",
        "roboguy_lambert4SG16",
        "roboguy_lambert4SG17",
        "roboguy_lambert4SG18",
        "roboguy_lambert4SG19",
        "roboguy_lambert4SG6",
    ])

    return {s for s in slot_names if len(s) >= 2 and not s.startswith(" ")}


def resolve_slot_material(
    slot_name: str,
    fbx_file_name: str,
    pack_name: str,
    available_materials: Dict[str, str],
    default_atlas_mat: str
) -> str:
    slot_lower = slot_name.lower()
    fname_lower = fbx_file_name.lower().replace(".fbx", "")

    # 1. Target Holograms
    if "target_hologram" in fname_lower or "holotarget" in slot_lower or ("target" in slot_lower and "holo" in fname_lower):
        for k in ["hologram_targets_01", "hologram_targets", "hologram_01"]:
            if k in available_materials:
                return available_materials[k]

    # 2. Hologram Signs
    if "holo_sign" in fname_lower or "holosign" in slot_lower:
        for k in ["hologram_signs_01", "hologram_signs", "hologram_01"]:
            if k in available_materials:
                return available_materials[k]

    # 3. Hologram Posters & Text
    if "holo_poster" in fname_lower:
        for k in ["hologram_posters_01_a", "hologram_posters_01_b", "hologram_01"]:
            if k in available_materials:
                return available_materials[k]
    if "holo_text" in fname_lower:
        for k in ["hologram_text_01", "hologram_01"]:
            if k in available_materials:
                return available_materials[k]

    # 4. Hologram Trees & Cherry Trees
    if "hologram_tree" in fname_lower or "hologram_cherry_tree" in fname_lower:
        for k in ["hologram_01", "hologram_basic_01_a"]:
            if k in available_materials:
                return available_materials[k]

    # 5. Hologram Stands & Tables
    if ("hologram_stand" in fname_lower or "hologram_table" in fname_lower or "holo_planter" in fname_lower) and ("holo" in slot_lower or "screen" in slot_lower):
        for k in ["hologram_01", "hologram_basic_01_a"]:
            if k in available_materials:
                return available_materials[k]

    # 6. Generic Holograms
    if "holo" in slot_lower or "hologram" in slot_lower:
        for k in ["hologram_01", "hologram_basic_01_a"]:
            if k in available_materials:
                return available_materials[k]

    # 7. Posters
    if "poster" in fname_lower or "poster" in slot_lower or "papers" in slot_lower:
        for k in ["posters_01", "poster_01", "papers_01"]:
            if k in available_materials:
                return available_materials[k]

    # 8. Billboards
    if "damaged_sign" in fname_lower or "billboard_damaged" in fname_lower:
        for k in ["billboard_01_damaged", "billboard_02_damaged", "billboard_01_a"]:
            if k in available_materials:
                return available_materials[k]
    if "billboard_sign_small" in fname_lower or "billboard_backing_small" in fname_lower:
        for k in ["billboard_03", "billboard_01_a"]:
            if k in available_materials:
                return available_materials[k]
    if "billboard" in fname_lower or "billboard" in slot_lower:
        for k in ["billboard_01_a", "billboard_02_a", "billboard_03"]:
            if k in available_materials:
                return available_materials[k]

    # 9. Signs & Neon
    if "neonsign" in fname_lower or "sign" in fname_lower or "sign" in slot_lower:
        for k in ["signs_01", "billboard_03", "billboard_01_a"]:
            if k in available_materials:
                return available_materials[k]

    # 10. Glass & Windows
    if "glass" in slot_lower or "glass" in fname_lower:
        for k in ["glass_01_a", "glass_transparent_01", "glass_01", "glass"]:
            if k in available_materials:
                return available_materials[k]

    # 11. Trash & Junk
    if "trash" in slot_lower or "trash" in fname_lower:
        for k in ["trash_01", "junk_01"]:
            if k in available_materials:
                return available_materials[k]
    if "junk_large" in fname_lower:
        for k in ["junk_large_01", "junk_01"]:
            if k in available_materials:
                return available_materials[k]
    if "junk" in fname_lower:
        for k in ["junk_01"]:
            if k in available_materials:
                return available_materials[k]

    # 12. FX & Lasers
    if "laser_grid" in fname_lower:
        for k in ["laser_grid_01", "laser_01"]:
            if k in available_materials:
                return available_materials[k]
    if "laser" in fname_lower:
        for k in ["laser_01"]:
            if k in available_materials:
                return available_materials[k]
    if "fx_leaf" in fname_lower or "fx_leaves" in fname_lower:
        for k in ["fx_leaves_01", "fx_leaves_02", "fx_leaves_03"]:
            if k in available_materials:
                return available_materials[k]
    if "fx_lightray" in fname_lower:
        for k in ["fx_lightray_01", "fx_lightray_02"]:
            if k in available_materials:
                return available_materials[k]
    if "fx_fish" in fname_lower:
        for k in ["fx_fish_pixel_01"]:
            if k in available_materials:
                return available_materials[k]
    if "fx_gradient" in fname_lower:
        for k in ["fx_gradient_01"]:
            if k in available_materials:
                return available_materials[k]

    # 13. Parallax Buildings & Modular Blocks
    if "sm_bld_block_" in fname_lower or "parallax" in fname_lower or "parallax" in slot_lower:
        for k in ["parallax_full_01", "parallax_01", "parallax"]:
            if k in available_materials:
                return available_materials[k]

    # 14. Walls, Bricks, Floors
    if "wall" in slot_lower or "a_wall" in slot_lower or "brick" in slot_lower or "stucco" in slot_lower or "floor" in slot_lower:
        num_match = re.search(r"(\d+)", slot_name)
        if num_match:
            target_key = f"wall_{num_match.group(1).zfill(2)}"
            for k in [f"{target_key}_a", f"{target_key}_b", target_key]:
                if k in available_materials:
                    return available_materials[k]
        for k, v in available_materials.items():
            if "wall_01_a" in k or "wall" in k or "brick" in k or "floor" in k:
                return v

    # 15. Nature & Environment
    if "tree" in slot_lower or "rock" in slot_lower or "mountain" in slot_lower or "water" in slot_lower:
        for k, v in available_materials.items():
            if any(term in k for term in ["tree", "rock", "mountain", "water", "nature"]):
                return v

    # 16. Specific pack alt textures if model stem specifies it (e.g. _01_B, _02_A, etc.)
    for suffix in ["_01_b", "_01_c", "_02_a", "_02_b", "_02_c", "_03_a", "_03_b", "_03_c", "_04_a", "_04_b", "_04_c"]:
        if fname_lower.endswith(suffix):
            for k, v in available_materials.items():
                if suffix[1:] in k:
                    return v

    return default_atlas_mat


def clean_and_normalize_import_content(content: str, post_import_script: str) -> str:
    """
    Removes invalid flags, strips trailing/duplicate fbx parameters,
    and removes old _subresources blocks using exact brace-depth counting.
    """
    # 1. Remove valid=false
    content = content.replace("valid=false\n", "").replace("valid=false", "")

    # 2. Remove all fbx/ lines so we can place fbx/importer=0 cleanly in [params]
    content = re.sub(r"fbx/importer=\d+\n?", "", content)
    content = re.sub(r"fbx/allow_geometry_helper_nodes=.*\n?", "", content)
    content = re.sub(r"fbx/embedded_image_handling=.*\n?", "", content)
    content = re.sub(r"fbx/naming_version=.*\n?", "", content)

    # 3. Cleanly remove old _subresources block using proper brace depth
    sub_idx = content.find("_subresources=")
    if sub_idx != -1:
        brace_start = content.find("{", sub_idx)
        if brace_start != -1:
            depth = 0
            end_idx = len(content)
            for i in range(brace_start, len(content)):
                if content[i] == "{":
                    depth += 1
                elif content[i] == "}":
                    depth -= 1
                    if depth == 0:
                        end_idx = i + 1
                        break
            content = content[:sub_idx].rstrip() + "\n" + content[end_idx:].lstrip()

    # 4. Clear import_script to let Godot 4 native _subresources handle materials cleanly
    content = re.sub(r'import_script/path="[^"]*"', 'import_script/path=""', content)

    # 5. Insert fbx/importer=0 under [params]
    params_idx = content.find("[params]")
    if params_idx != -1:
        content = content[:params_idx + 8] + "\nfbx/importer=0" + content[params_idx + 8:]

    return content.strip()


def map_pack_fbx_models(pack_dir: str, project_root: str) -> Tuple[int, int]:
    available_materials = find_pack_materials(pack_dir, project_root)
    pack_name = os.path.basename(pack_dir)

    default_atlas_mat = ""
    for k, v in available_materials.items():
        if "01_a" in k:
            default_atlas_mat = v
            break
    if not default_atlas_mat and available_materials:
        default_atlas_mat = next(iter(available_materials.values()))

    total_models = 0
    total_slots = 0
    post_import_script = "res://synty_post_import.gd"

    for root, dirs, files in os.walk(pack_dir):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        for f in files:
            if f.endswith(".fbx"):
                fbx_path = os.path.join(root, f)
                import_path = fbx_path + ".import"
                if not os.path.exists(import_path):
                    continue

                slot_names = extract_fbx_material_slots(fbx_path)
                material_lines = []

                for slot in sorted(slot_names):
                    target_mat = resolve_slot_material(slot, f, pack_name, available_materials, default_atlas_mat)
                    material_lines.append(
                        f'"{slot}": {{\n"use_external/enabled": true,\n"use_external/path": "{target_mat}"\n}}'
                    )
                    total_slots += 1

                materials_subresources = ",\n".join(material_lines)
                subresources_block = f'_subresources={{\n"materials": {{\n{materials_subresources}\n}}\n}}'

                with open(import_path, "r", encoding="utf-8", errors="ignore") as fo:
                    raw_content = fo.read()

                cleaned_base = clean_and_normalize_import_content(raw_content, post_import_script)
                final_content = cleaned_base + "\n\n" + subresources_block + "\n"

                with open(import_path, "w", encoding="utf-8") as fo:
                    fo.write(final_content)

                total_models += 1

    return total_models, total_slots
